### ISSUE TITLE
Dataset link is missing :(

### ISSUE THREAD

**Issue by elorberb** [RecList/evalRS-CIKM-2022#12]
Hello,

I was wondering if the evalrs_dataset.zip data from the competition is still accessible via the link provided in the LFM_DATASET_PATH variable. I am engaged in an academic course where my goal is to replicate and analyze the results presented in several papers published as part of this competition. Unfortunately, the current link appears to be non-functional for me. Could you please advise if there's an alternative method or link available for accessing the dataset?

Thank you.

**Comment by jacopotagliabue** [comment]
Hi @elorberb thanks for reaching out - we are not working anymore for the company that hosted the original dataset on S3 as part of our open competition, so unfortunately we have no way to verify that link. I'll do some digging and see if we have copies, but it looks unlikely.
